### PR TITLE
Use raiden libs

### PR DESCRIPTION
**Pull request by palango**
This PR changes most of our own test fixtures to the ones implemented in raiden-libs. Support for multiple token networks will be added later.

### CODE REVIEW

**Comment by devium** [comment]
Why did you reduce fixtures to a single token network? Because they are currently not used?

**Comment by palango** [comment]
Mostly because Jozefs fixtures don't have support for multiple networks at the moment and because it isn't used at the moment.

**Comment by pcppcp** [comment]
Shouldn't be hard to add multiple token support. Let me work on that.

**Comment by devium** [comment]
Let's wait for that then.

**Comment by pcppcp** [comment]
https://github.com/raiden-network/raiden-libs/pull/24

**Comment by LefterisJP** [comment]
@palango This PR needs some love and rebasing on top of Jozef's changes.

**Pull request merged**
